[package]
name        =  "rdrs"
version     =  "0.0.1"
description =  "Read Rust"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license     =  "MIT"
repository  =  "https://github.com/ponyatov/rdrs"
edition     =  "2024"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[lib]
name        =  "librdrs"
path        =  "src/lib.rs"
crate-type  = ["cdylib"]

[dependencies]
const_format = "0.2"
nom          = "8.0"
page_size    = "0.6"

[target.'cfg(all(target_os = "linux"))'.dependencies]
libc    = "0.2"
memmap2 = "0.9"
sdl2    = {version = "0.38", features = ["ttf","image"], optional = true}

[dev-dependencies]
criterion = "0.7"

[features]

# hw
pc              = ["i5"]
# cpu
i5              = ["x86_64"]
# arch
x86_64          = ["linux"]
# os
linux           = []
# gui variant
sdl             = ["dep:sdl2"]
