[build]
target = "x86_64-unknown-linux-gnu"
jobs = 2

[target.x86_64-unknown-linux-gnu]
# features = ["pc","i5","x86_64","linux"]
linker   = "x86_64-linux-gnu-gcc"

[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
[source.tsinghua]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"
